work1/config/routes.rb
Rails.application.routes.draw do
  root 'labs#index'

  resources :labs

  get '/labs/:id/mark', to: 'labs#mark', as: 'mark_lab'

  post '/labs/:id/mark', to: 'labs#grade'
end

work1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

work1/app/models/lab.rb
class Lab < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 250 }
  validates :description, length: { maximum: 250 }
end

work1/app/models/user.rb
class User < ApplicationRecord
  has_many :labs

  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
end

work1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
end

work1/app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

work1/app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :find_lab, only: %i[show update destroy edit mark grade]

  def index
    @labs = Lab.all
  end

  def show
  end

  def new
    @lab = Lab.new
  end

  def create
    @lab = Lab.new(lab_params)
    @lab.user_id = 1

    if @lab.save
      redirect_to root_url
      flash[:success] = "Lab was created successfully"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if (@lab.update(lab_params))
      redirect_to root_url
      flash[:success] = "Lab was updated successfully"
    else
      render 'edit'
    end
  end

  def mark
  end

  def grade
    if (@lab.update(params.permit(:grade)))
      redirect_to root_url
      flash[:success] = "Mark was added successfully"
    else
      render 'mark'
    end
  end

  def destroy
    @lab.destroy

    redirect_to action: :index
    flash[:success] = "Lab was deleted successfully"
  end

  private

  def find_lab
    @lab = Lab.find params[:id]
  end

  def lab_params
    params.require(:lab).permit(:title, :description)
  end
end

work1/app/helpers/application_helper.rb
module ApplicationHelper
end

work1/app/helpers/labs_helper.rb
module LabsHelper
end

work1/app/views/labs/_form.html.erb
<%= form_with model: @lab do |f|%>
  <% if @lab.errors.any?%>
    <% @lab.errors.full_messages.each do |msg|%>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <h4>Title</h4>
    <%= f.text_field :title, required: true%><br>

  <h4>Description</h4>
    <%= f.text_area :description, {:class => 'form-control'}%><br>

    <%= f.submit({:class => 'btn btn-success'}) %>
    <button type="button" class="btn btn-secondary"><%= link_to "Back", root_path%></button>
<% end %>

work1/app/views/labs/edit.html.erb
<h2>Editing new lab</h2><br>

<%= render 'form' %>

work1/app/views/labs/index.html.erb
<h1>All Labs</h1><br>

<button type="button" class="btn btn-outline-primary"><%= link_to "Upload new lab", new_lab_path%></button><br><br>

<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

<table class="table">
  <thead>
    <th scope="col">Title</th>
    <th scope="col">Description</th>
    <th scope="col">Grade</th>
  </thead>

  <tbody>
    <% @labs.each do |lab| %>
      <tr>
        <td><%= lab.title %></td>
        <td><%= lab.description %></td>
        <td><%= lab.grade %></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to "Edit", edit_lab_path(lab) %></button></td>
        <td><button type="button" class="btn btn-outline-secondary"><%= link_to "Show", lab_path(lab) %></button></td>
        <td><button type="button" class="btn btn-outline-warning"><%= link_to "Add mark", mark_lab_path(lab) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to "Delete", lab_path(lab), method: :delete, data: {confirm: "Are you sure?"} %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

work1/app/views/labs/mark.html.erb
<h2>Adding mark</h2><br>

<%= form_with url: mark_lab_path(@lab) do |f| %>
  <% if @lab.errors.any?%>
    <% @lab.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <h4>Grade</h4>
    <%= f.text_field :grade, {:class => 'form-control'} %><br>

    <%= f.submit({:class => 'btn btn-success'}) %>
    <button type="button" class="btn btn-secondary"><%= link_to "Back", root_path %></button>
<% end %>

work1/app/views/labs/new.html.erb
<h2>Adding new lab</h2><br>

<%= render 'form' %>

work1/app/views/labs/show.html.erb
<h1>Title: <%= @lab.title %></h1><br>
<h2>Description: <%= @lab.description %></h2><br>
<h2>Grade: <%= @lab.grade %></h2><br>
<button type="button" class="btn btn-primary"><%= link_to "Edit", edit_lab_path(@lab) %></button>
<button type="button" class="btn btn-secondary"><%= link_to "Back", labs_path %></button>
<button type="button" class="btn btn-warning"><%= link_to "Add mark", mark_lab_path %></button>

work1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      a {
       text-decoration: none;
       color: black
      }
   </style>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>